### ISSUE TITLE
NameLengthBypass is not working

### ISSUE THREAD

**Issue by Hacks-lol** [ThatFruedDued/kahoot-smasher#2]
there was a update and the hack is not working

**Comment by ThatFruedDued** [comment]
Please describe your issue in greater detail (like the specific issue rather than just "is not working".) This will make it easier for me to find the issue in the script and fix it.

**Comment by Hacks-lol** [comment]
sorry i mean theres only the put limit
its not bypassing anymore, so i cant do long names anymore

**Comment by Aethese** [comment]
just a heads up to anyone having this problem, the bypass still works. all you have to do now is change the "maxLimit" value to something absurdly long with inspect element
